/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppStudentsRouteImport } from './routes/app.students'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppMusireelsRouteImport } from './routes/app.musireels'
import { Route as AppMessagesRouteImport } from './routes/app.messages'
import { Route as AppInstructorsRouteImport } from './routes/app.instructors'
import { Route as AppAnalyzeRouteImport } from './routes/app.analyze'
import { Route as AppInstructorsIndexRouteImport } from './routes/app.instructors.index'
import { Route as AppLearnerUserIdRouteImport } from './routes/app.learner.$userId'
import { Route as AppInstructorsIdRouteImport } from './routes/app.instructors.$id'
import { Route as AppAnalyzeResultRouteImport } from './routes/app.analyze.result'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsRoute = AppStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppMusireelsRoute = AppMusireelsRouteImport.update({
  id: '/musireels',
  path: '/musireels',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppInstructorsRoute = AppInstructorsRouteImport.update({
  id: '/instructors',
  path: '/instructors',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyzeRoute = AppAnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => AppRoute,
} as any)
const AppInstructorsIndexRoute = AppInstructorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppInstructorsRoute,
} as any)
const AppLearnerUserIdRoute = AppLearnerUserIdRouteImport.update({
  id: '/learner/$userId',
  path: '/learner/$userId',
  getParentRoute: () => AppRoute,
} as any)
const AppInstructorsIdRoute = AppInstructorsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppInstructorsRoute,
} as any)
const AppAnalyzeResultRoute = AppAnalyzeResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => AppAnalyzeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/app/analyze': typeof AppAnalyzeRouteWithChildren
  '/app/instructors': typeof AppInstructorsRouteWithChildren
  '/app/messages': typeof AppMessagesRoute
  '/app/musireels': typeof AppMusireelsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/students': typeof AppStudentsRoute
  '/app/': typeof AppIndexRoute
  '/app/analyze/result': typeof AppAnalyzeResultRoute
  '/app/instructors/$id': typeof AppInstructorsIdRoute
  '/app/learner/$userId': typeof AppLearnerUserIdRoute
  '/app/instructors/': typeof AppInstructorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/app/analyze': typeof AppAnalyzeRouteWithChildren
  '/app/messages': typeof AppMessagesRoute
  '/app/musireels': typeof AppMusireelsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/students': typeof AppStudentsRoute
  '/app': typeof AppIndexRoute
  '/app/analyze/result': typeof AppAnalyzeResultRoute
  '/app/instructors/$id': typeof AppInstructorsIdRoute
  '/app/learner/$userId': typeof AppLearnerUserIdRoute
  '/app/instructors': typeof AppInstructorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/app/analyze': typeof AppAnalyzeRouteWithChildren
  '/app/instructors': typeof AppInstructorsRouteWithChildren
  '/app/messages': typeof AppMessagesRoute
  '/app/musireels': typeof AppMusireelsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/students': typeof AppStudentsRoute
  '/app/': typeof AppIndexRoute
  '/app/analyze/result': typeof AppAnalyzeResultRoute
  '/app/instructors/$id': typeof AppInstructorsIdRoute
  '/app/learner/$userId': typeof AppLearnerUserIdRoute
  '/app/instructors/': typeof AppInstructorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/app/analyze'
    | '/app/instructors'
    | '/app/messages'
    | '/app/musireels'
    | '/app/profile'
    | '/app/students'
    | '/app/'
    | '/app/analyze/result'
    | '/app/instructors/$id'
    | '/app/learner/$userId'
    | '/app/instructors/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/app/analyze'
    | '/app/messages'
    | '/app/musireels'
    | '/app/profile'
    | '/app/students'
    | '/app'
    | '/app/analyze/result'
    | '/app/instructors/$id'
    | '/app/learner/$userId'
    | '/app/instructors'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/app/analyze'
    | '/app/instructors'
    | '/app/messages'
    | '/app/musireels'
    | '/app/profile'
    | '/app/students'
    | '/app/'
    | '/app/analyze/result'
    | '/app/instructors/$id'
    | '/app/learner/$userId'
    | '/app/instructors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/students': {
      id: '/app/students'
      path: '/students'
      fullPath: '/app/students'
      preLoaderRoute: typeof AppStudentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/musireels': {
      id: '/app/musireels'
      path: '/musireels'
      fullPath: '/app/musireels'
      preLoaderRoute: typeof AppMusireelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/messages': {
      id: '/app/messages'
      path: '/messages'
      fullPath: '/app/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/instructors': {
      id: '/app/instructors'
      path: '/instructors'
      fullPath: '/app/instructors'
      preLoaderRoute: typeof AppInstructorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analyze': {
      id: '/app/analyze'
      path: '/analyze'
      fullPath: '/app/analyze'
      preLoaderRoute: typeof AppAnalyzeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/instructors/': {
      id: '/app/instructors/'
      path: '/'
      fullPath: '/app/instructors/'
      preLoaderRoute: typeof AppInstructorsIndexRouteImport
      parentRoute: typeof AppInstructorsRoute
    }
    '/app/learner/$userId': {
      id: '/app/learner/$userId'
      path: '/learner/$userId'
      fullPath: '/app/learner/$userId'
      preLoaderRoute: typeof AppLearnerUserIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/instructors/$id': {
      id: '/app/instructors/$id'
      path: '/$id'
      fullPath: '/app/instructors/$id'
      preLoaderRoute: typeof AppInstructorsIdRouteImport
      parentRoute: typeof AppInstructorsRoute
    }
    '/app/analyze/result': {
      id: '/app/analyze/result'
      path: '/result'
      fullPath: '/app/analyze/result'
      preLoaderRoute: typeof AppAnalyzeResultRouteImport
      parentRoute: typeof AppAnalyzeRoute
    }
  }
}

interface AppAnalyzeRouteChildren {
  AppAnalyzeResultRoute: typeof AppAnalyzeResultRoute
}

const AppAnalyzeRouteChildren: AppAnalyzeRouteChildren = {
  AppAnalyzeResultRoute: AppAnalyzeResultRoute,
}

const AppAnalyzeRouteWithChildren = AppAnalyzeRoute._addFileChildren(
  AppAnalyzeRouteChildren,
)

interface AppInstructorsRouteChildren {
  AppInstructorsIdRoute: typeof AppInstructorsIdRoute
  AppInstructorsIndexRoute: typeof AppInstructorsIndexRoute
}

const AppInstructorsRouteChildren: AppInstructorsRouteChildren = {
  AppInstructorsIdRoute: AppInstructorsIdRoute,
  AppInstructorsIndexRoute: AppInstructorsIndexRoute,
}

const AppInstructorsRouteWithChildren = AppInstructorsRoute._addFileChildren(
  AppInstructorsRouteChildren,
)

interface AppRouteChildren {
  AppAnalyzeRoute: typeof AppAnalyzeRouteWithChildren
  AppInstructorsRoute: typeof AppInstructorsRouteWithChildren
  AppMessagesRoute: typeof AppMessagesRoute
  AppMusireelsRoute: typeof AppMusireelsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppStudentsRoute: typeof AppStudentsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppLearnerUserIdRoute: typeof AppLearnerUserIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyzeRoute: AppAnalyzeRouteWithChildren,
  AppInstructorsRoute: AppInstructorsRouteWithChildren,
  AppMessagesRoute: AppMessagesRoute,
  AppMusireelsRoute: AppMusireelsRoute,
  AppProfileRoute: AppProfileRoute,
  AppStudentsRoute: AppStudentsRoute,
  AppIndexRoute: AppIndexRoute,
  AppLearnerUserIdRoute: AppLearnerUserIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
